- src/handler.rs
- src/handlers/initialize.rs
- src/lib.rs
- src/main.rs
- src/protocol/responses.rs
- tests/handlers.rs
VScode runs better when folding range provider is disabled, this feature provides a flag, to disable the server's folding range capacity.
> feat(src): add flag to disable the folding range

- Cargo.lock
- Cargo.toml
`flux::semantic::analyze_source` was recently updated with a breaking change. This commit updates the flux dependency to a stable commit.
> dep: remove dependency on flux master

- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/protocol/properties.rs
- src/protocol/responses.rs
Closes #https://github.com/influxdata/flux-lsp/issues/64
Vscode plugin doesn't auto send didOpen request, is due to we are missing a server capacity described in https://github.com/microsoft/language-server-protocol/blob/master/versions/protocol-2-x.md
TextDocumentSyncKind
This pr will fix the issue, manually tested.
> fix(src/protocol): add server cap of text sync

- Cargo.lock
- Cargo.toml
Closes https://github.com/influxdata/flux-lsp/issues/104
bump the version, manually tested
> chore(config): bump the flux version

- Makefile
- Readme.md
Small PR to add ability to run specific tests using make command.
> chore: update readme and extend makefile with ability to target tests

- Cargo.lock
- Cargo.toml
- src/stdlib/mod.rs
- src/visitors/semantic/completion/results.rs
- tests/handlers.rs
Closes #169 
Helps with #170 
This PR accomplishes 3 things:
- Imports the latest release of Flux
- Replaces `MonoType::Row` with `MonoType::Record` and mirrors that rename in `VarType` enum
- Changes expected results in a few tests in `tests/handlers.rs`
Some of the tests in `tests/handlers.rs` are flimsy, and will need to be replaced with more more robust tests (as per #174). Changing the expected result should be sufficient for now, but it should be noted that this is only a temporary solution.
> refactor(lsp): Replace MonoType::Row with MonoType::Record

- Dockerfile
This might fix #176 by adding an official git client to the image
> fix(Dockerfile): add git to dockerfile for build

- Cargo.lock
- Cargo.toml
- Makefile
- src/cache/mod.rs
- src/handlers/completion.rs
- src/handlers/completion_resolve.rs
- src/handlers/document_change.rs
- src/handlers/document_close.rs
- src/handlers/document_formatting.rs
- src/handlers/document_open.rs
- src/handlers/document_save.rs
- src/handlers/document_symbol.rs
- src/handlers/folding.rs
- src/handlers/goto_definition.rs
- src/handlers/hover.rs
- src/handlers/initialize.rs
- src/handlers/mod.rs
- src/handlers/references.rs
- src/handlers/rename.rs
- src/handlers/router.rs
- src/handlers/shutdown.rs
- src/handlers/signature_help.rs
- src/lib.rs
- src/shared/ast.rs
- src/shared/conversion.rs
- src/shared/mod.rs
- src/stdlib/mod.rs
- src/visitors/ast/package_finder.rs
- src/visitors/semantic/utils.rs
- tests/handlers.rs
This change removes the global file cache and instead injects the
dependency into every function call that needed access to the cache.
The global cache meant that the test could not be run in parallel i.e.
multiple threads otherwise they would conflict on the global cache.
This change also makes the uri parameter to function a &str instead of a
String. This was because the string was being copied for every call into
the cache for the uri. Now the uri is only copied when it actually
stored in the cache etc.
Finally one test case was remove about multiple packages as it was
asserting internal details of how the router behaves via the global
cache.
Fixes #173
Describe your proposed changes here.
> refactor(cache): removes global cache

- Dockerfile
CircleCI spits out this error when running the `deploy` job:
```
Either git or ssh (required by git to clone through SSH) is not installed in the image. Falling back to CircleCI's native git client but the behavior may be different from official git. If this is an issue, please use an image that has official git and ssh installed.
Enumerating objects: 141, done.
Counting objects: 100% (141/141), done.
Compressing objects: 100% (102/102), done.
Total 1368 (delta 62), reused 73 (delta 32), pack-reused 1227
reference not found
```
This PR adds `openssh` to the list of dependencies to be installed when building the `wasm-build` image.
> build(dockerfile): install openssh in wasm-build docker image

- Cargo.toml
- bump-version.sh
- Imports Flux 0.91.0
- `bump-version.sh` sets upstream and pushes to new github branch, rather than trying to push to master
- Increment version to 0.5.21
> build: Increment version

- Cargo.lock
- Cargo.toml
- src/handlers/completion.rs
- src/handlers/completion_resolve.rs
- src/handlers/document_change.rs
- src/handlers/document_close.rs
- src/handlers/document_formatting.rs
- src/handlers/document_open.rs
- src/handlers/document_save.rs
- src/handlers/document_symbol.rs
- src/handlers/folding.rs
- src/handlers/goto_definition.rs
- src/handlers/hover.rs
- src/handlers/initialize.rs
- src/handlers/mod.rs
- src/handlers/references.rs
- src/handlers/rename.rs
- src/handlers/router.rs
- src/handlers/shutdown.rs
- src/handlers/signature_help.rs
- src/wasm/mod.rs
- tests/handlers.rs
This change uses an error struct instead of string for error handling,
this makes it easier to implement From traits on the error type for the
various kinds of error we might encounter.
Do NOT merge in this state, it points at Flux master in order to bring in recent changes the formatter. Its safe to merge as part of the upgrade to the next version of Flux.
> feat(handlers): use a error struct for error handling

- Cargo.lock
- Cargo.toml
* Upgrades wasm-bindgen crates to most recent releases
* Adds configuration options for `wasm-opt` to `Cargo.toml` to fix failed compilations while still allowing for optimizations.
> build(wasm): Upgrade wasm-bindgen crates + changes to wasm-opt config

- src/shared/callbacks.rs
`register_blahblah_callback` methods now just set callbacks to `None`. After failing to find a proper fix for #190, @nathanielc and I determined that it was best to just disable the feature until we can settle on a better solution.
> fix(callbacks): Disable callbacks for user data

- Cargo.lock
- Cargo.toml
- Change version from v0.5.26 to v0.5.27
- Upgrade Flux to [v0.100.1](https://github.com/influxdata/flux/releases/tag/v0.100.1)
> build: Bump to v0.5.27

- Cargo.lock
- Cargo.toml
- Change version from v0.5.32 to v0.5.33
- Upgrade to [Flux v0.106.0](https://github.com/influxdata/flux/releases/tag/v0.106.0)
> build: Bump to v0.5.33

- .circleci/config.yml
- Cargo.toml
- src/handlers/document_save.rs
- src/handlers/goto_definition.rs
- src/lib.rs
- src/shared/mod.rs
- src/visitors/semantic/completion/utils.rs
- src/wasm/mod.rs
In flux, we have a pretty standard process that we use for building rust
code. We deny warnings, we enforce style with fmt checks, and we check
lint with clippy. This patch brings flux-lsp more in-line with flux, and
fixes outstanding issues that occurred as a result of the new stricter
checks.
> chore: modify rust toolchain to be more like flux

- consume-lsp.sh
We've confirmed that the release script added here works on both mac and linux devices, provided some prerequisites have been met. I'm adding this to source control so that anyone can use the script.
> chore: Commit release script

- Dockerfile
The newest release of flux, 1.119.0, included changes that won't work on
the old version of rust in the current wasm-build image. That exposed
the problem that we were on an ancient rust. When upgrading, I noticed
that we were still using the `curl | sh` pattern we've been trying to
avoid. The best way to combat that was to just use the `flux-build`
image that we use in flux.
The only remaining need for the wasm-build image was nodejs, which
_also_ used the `curl | sh` pattern, so I took the time to read the
downloaded script and did the tasks (albeit less smart) that the script
did, only manually.
> feat: inherit build setup from flux-build

- Cargo.toml
Auditing dependencies, some of these (slightly older) dependencies
allowed for versions of their dependencies with open vulnerabilities. In
general, this didn't necessarily affect this library, because we don't
commit `Cargo.lock` and the default is to take the most up-to-date, but
this change will force updates to stale `Cargo.lock` files on dev
machines.
> fix: update dependencies to most recent versions

- .circleci/config.yml
This patch makes the ci jobs parallelized rather than serial. This is a
good idea when there is a credit limit on CircleCI, but the `influxdata`
credit budget allows for parallelizing these tasks.
> chore: parallelize ci jobs

- Dockerfile
Undoing this mistake: https://github.com/influxdata/flux-lsp/commit/27ff301f62a5e0d29a9db32311b73bf1bb462e32#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557L15-R15
> chore: Revert USER to UNAME in dockerfile

- lsp-release.sh
- Prepend the version number with `v` when linking to the Flux release in the lsp release notes
- Reference `$branch` instead of `$branch_name` in `bump_npm_version` function
> chore: Fix release notes + typos in release script

- lsp-release.sh
Removed a check that was consistently hitting false-positives and interrupting the release script. Also fixed a link in the lsp release notes.
> chore: Fix release notes in script and remove check for duplicate releases

- src/handlers/mod.rs
- src/handlers/signature_help.rs
- src/server.rs
This patch implements the `textDocument/signatureHelp` lsp call, with
accompanying tests. As a by-product of this work, `textDocument/didOpen`
as well, since the signature help requires that the document be open.
Fixes #243
Fixes #252
> feat: implement textDocument/signatureHelp

- src/lib.rs
- src/macros.rs
> Flat is better than nested.
This patch merges the 4 lines from the `macros` module into the core
`lib.rs` file and removes the `macros.rs` file.
> chore: consolidate macros module

- Cargo.toml
- src/handlers/tests.rs
- src/server.rs
This patch implements `textDocument/formatting` in the new lsp server.
While working on this issue, a problem was discovered in the old
implementation whereby the ranges, likely across the board, were
incorrect. They were left as is, but an explicit assertion on the
existing test was added, with a comment demonstrated its correctness
issues.
Closes #242
> feat: implement textDocument/formatting

- Cargo.toml
- src/server.rs
This patch implements the `textDocument/didChange` rpc call in the
`lspower` server. At this point, the absolutely critical pieces of the
lsp are supported. There is one new piece of functionality in this new
lsp server over the original, and that is the ability to update only a
range of the document, rather than sending the whole file across to the
server.
There is one specific caveat to call out here: the lsp protocol spec
specifically speaks about versioned documents, and has corresponding
data structures that the client can send the server on change events.
It's not clear from the protocol what that versioning _does_, as it
doesn't seem to be read out anywhere, only set. The current lsp server
writes those versions, but it never reads them out; it overwrites with
each …
> feat: implement textDocument/didChange

- integration/lsp.test.ts
- src/cache.rs
- src/handlers/mod.rs
- src/handlers/tests.rs
- src/lib.rs
- src/protocol/properties.rs
- src/protocol/responses.rs
- src/shared/messages.rs
- src/wasm.rs
Building on the knowledge and assertions made by the existence of the
integration tests added in #274, this patch reduces the public interface
provided by the `flux-lsp` lib.
This means that _nothing_ is exposed in the `flux-lsp` lib, but there
are still things exported via `wasm_bindgen`, and they are denoted in
the source properly and enforced with the integration tests.
> chore: reduce the public interface

- src/bin/flux-lsp.rs
- src/server.rs
This patch introduces the builder pattern to the `LspServer`. This work
was a spike in building out a couple of different ways to create an
`LspServer` instance. In the default main case, an `LspServer::new()` is
all that's needed, and doing `LspServer::new(true, None, None, None)` is
less clear about what the random `bool` and `Option` args are.
> feat: use the builder pattern for LspServer

- Cargo.toml
- src/bin/flux-lsp.rs
- src/server.rs
This patch removes tokio from the equation, and moves to using
`async_std` instead. It's _possible_ that there may one day be a case
for using `tokio` again, and at that point, we'll enable it using
feature flag.
> feat: make the lsp server platform agnostic

- src/server.rs
Closes #251
The main chunk of logic I had to work on was the `find_references` function. It seems to make the test pass, but I think I could use an extra set of eyes on it. [This](https://github.com/rockstar/flux-lsp/blob/40f7edd5c651888542e608a096c0ae09cb3c1753/src/server.rs#L66-L128) was the original implementation when I started working on it, and it looks like it was mostly copied from [here](https://github.com/influxdata/flux-lsp/blob/69e9fd48f0c56695dcd568d57726ba6bfab9a5a2/src/handlers/references.rs#L81-L117). I just tried to clean it up a bit.
> feat(lspower): Implement rename handler for lspower server

- src/server.rs
Closes #250
Most of the logic for this was already implemented in #280
One thing I'd like to call attention to is the fact that we are currently not referencing the `declaration_included` field in the `ReferenceParams`. Not sure if we care about that or not.
> feat(lspower): Implement textDocument/references handler

- src/convert.rs
- src/handlers/goto_definition.rs
- src/handlers/references.rs
- src/lib.rs
- src/server.rs
- src/shared/conversion.rs
> Position in a text document expressed as zero-based line and zero-based character offset.
I genuinely feel kinda gaslit, because I thought for sure I read that it
was the opposite of what the spec says, but the spec says positions are
zero-based. This patch attempts to fix those issues, though I suspect
that it's actually going to be an ongoing process.
> fix: attempt to fix many off-by-one errors

- .circleci/config.yml
- Cargo.toml
- integration/lsp.test.ts
- src/bin/flux-lsp.rs
- src/handlers/mod.rs
- src/lib.rs
- src/server.rs
- src/wasm2.rs
- wasm-build.sh
This patch adds the lsp server for the new lspower-based lsp server.
Closes #283
> feat: build the wasm interface for lsp2

- src/convert.rs
- src/server.rs
- src/stdlib.rs
- src/visitors/semantic/completion/utils.rs
The `textDocument/completionResolve` and `textDocument/hover` were
essentially no-ops in the previous server. They are implemented in a
not-very-useful way, but implemented nonetheless. This patch implements
both of those.
Additionally, it addresses some clippy lints.
> fix: address issues found in testing lsp2

- src/server.rs
Closes #239 
This patch does a few things:
1. Adds an implementation of the `completion()` method to the lspower server
2. Ports the completion-related tests from `src/handlers/tests.rs` into the test module for the lspower server
3. Copies any functions, data structures, or traits that are necessary to support autocompletion into `server.rs` and refactors them so that they no longer require a `RequestContext` or a `Cache` to function. Anything that was private or that required signature/definition changes got copied into `server.rs`. Everything else was left as-is and imported.
There's one outstanding test failure involving how the new LSP handles parse errors. The old LSP could convert parse errors into diagnostic notifications and still respond to completion requests. It appears this …
> feat(lspower): Implement completion handler

- src/lib.rs
- src/server.rs
- src/shared/ast.rs
- src/shared/callbacks.rs
- src/shared/conversion.rs
- src/shared/mod.rs
- src/shared/structs.rs
- src/stdlib.rs
- src/visitors/ast/package_finder.rs
- src/visitors/semantic/completion/mod.rs
- src/visitors/semantic/completion/utils.rs
- src/visitors/semantic/functions.rs
- src/visitors/semantic/mod.rs
This patch hides all non-lsp2 code behind a feature flag. This work was
needed two-fold: document code that can be deleted soon, and (b) shrink
the size of the resulting wasm binary. Unfortunately, the wasm binary is
mostly optimized already, so the size difference is pretty negligible.
> chore: hide non-lsp2 code behind cfg pragmas

- lsp-release.sh
The release script was a bit too specific to pulling in flux and
releasing. Additionally, it disconnects this release from the pulling in
of changes to vsflux and the flux-lsp-cli (which is deprecated and
likely to disappear soon).
> chore: rework release script

- Cargo.toml
- benches/server.rs
- src/server.rs
- src/visitors/ast.rs
This patch adds two benchmark tests, and the underlying setup required
to run those tests. This work was exploratory while chasing some
potential performance issues that I was experiencing in vsflux. It ended
up being informative but not entirely helpful. However, I think it's
still valuable work to commit.
Additionally, a file got reformatted and a visitor was deleted because
it wasn't used.
> chore: add some benchmark tests

- release.sh
In the same vein as the release script for influxdata/vsflux, this
script does the update of `Cargo.toml` and tag in one step and pushes to
master, causing the CI to then run and publishing to npm.
This script was used to tag/release 0.6.5, so I'm confident it works.
> chore: add a release script

- Cargo.toml
- src/convert.rs
- src/shared/mod.rs
- src/shared/signatures.rs
- src/visitors/ast.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/functions.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols.rs
`lspower` re-exports `lsp_types` as `lspower::lsp`. We were using the
straight `lsp_types` types as a way to transition between old lsp and
new lsp. The issue shows up when `lsp_types` gets updated, and then
thoses types are incompatible with the `lspower` types.
This patch removes `lsp_types` entirely and uses the `lspower::lsp`
types instead.
> chore: remove lsp_types

- src/bin/flux-lsp.rs
- src/lib.rs
- src/server.rs
- src/stdlib.rs
- src/wasm.rs
This patch removes all blind unwrap and panic. This came out of an
iterative need while designing the new API, as I had all sorts issues
where the wasm would stop working because of a panic, and while it was a
coding error, I'd rather get some sort of output.
> feat: no more unwrap/expect/panic

- rust-toolchain.toml
Per <https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file>
`rustup` will check cargo projects for a toolchain file and will fetch
the specified toolchain version if it isn't already present in
`$CARGO_HOME`.
In this, the toolchain file provides a _project-specific_ toolchain
override, allowing individual projects to be pinned to different
versions (if desired).
The intent here is to help unify the standards (lints) applied between
local dev and CI and also signal when a toolchain bump is expected.
Closes #
Describe your proposed changes here.
> chore: Add rust toolchain file.

- .circleci/config.yml
- Cargo.toml
- src/lib.rs
- src/wasm.rs
- src/wasm2.rs
This patch adds a new `Lsp` struct that represents the next
wasm-exported API for flux-lsp. It sits behind a `wasm_next` feature
flag, as it is still a work-in-progress and will need some extensive
testing before it's released.
This API has very small interface, and would look like this:
```
const { Lsp } = await import('@influxdata/flux-lsp-node');
const server = new Lsp();
server.onMessage((message) => {
// Handle the message
})
server.run();
const request = 'Content-Length: 83\r\n\r\n{...}';
await server.send(request)
```
The core change here is the message handler API, and `server.send`
(which is roughly equivalent `server.process` in the current api)
doesn't return a value anymore (though still returns a promise, for
async reasons). The message handler can now receive messages from …
> feat: add new wasm-export LSP API

- src/lib.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/mod.rs
- src/wasm2.rs
This patch converts the `Outgoing` interface to buffer writes and
then fire the event handlers when `flush` is called. The naive parsing
of bytes to messages has been made a bit more robust, but has a (noted)
glaring issue with it.
Much of this work will likely be heavily refactored/removed after the
fact. The important deliverable here is the external API, and everything
behind-the-scenes can be comfortably re-worked.
> feat: buffer the writes and fire on flush

- Cargo.lock
- Cargo.toml
- src/convert.rs
- src/server.rs
- src/stdlib.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/functions.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols.rs
This patch updates flux-lsp to work with flux `v0.143.1`. It highlights
a number of places where the code is poorly factored. There is a lot of
`String` use where it's probably not needed, and a copious amount of
`clone`-gone-`to_string` calls made. Rather than pulling on the thread
and watching a refactoring unravel everything, I opted for the smallest
change to get the newest flux formatter changes, will file more specific
issues to make things better in these other places.
> feat: update to flux v0.143.1

- src/completion.rs
- src/lib.rs
- src/server.rs
When we moved to `lspower`, we kinda just crammed everything into
`src/server.rs` so we knew what we needed and what we didn't. This patch
moves the completion code out of `server.rs` and into its own module.
Additionally, it shifts some imports around. No code changes were made;
this is all moved code.
> chore: create a completion module

- src/server.rs
Some of the holdover tests from the previous lsp weren't very specific, as
they asserted on the length of responses rather than contents. This patch
changes that to assert on the contents. "But wait," you might say.
"These tests only assert on labels and names." In these cases, I think 
that's okay, as the rest of the data structure isn't really used
(currently) by flux.
Fixes #174
> test: assert contents not len

- src/completion.rs
- src/server.rs
Some functionality was introduced in flux which is...well, sort of private.
It wouldn't be detrimental to know about and use, necessarily, but we don't
want the lsp to help users discover that functionality. This patch changes
the stdlib completion code to not complete items that start with an
underscore.
Fixes #308
> fix: don't complete stdlib items starting with underscore

- src/bin/flux-lsp.rs
- src/lib.rs
- src/server.rs
- src/wasm.rs
We always used the builder pattern, kinda. Not using a separate struct
certainly carried with it some baggage, which makes it clear why it's
usually implemented that way. This patch rectifies that.
Additionally, it removes some of the options from `LspServerOptions`
because they never should have been there in the first place. Holding on
to secrets and uris isn't really the job of the lsp server, and we
should explicitly forbid that as a pattern.
> feat: add an LspServerBuilder

- integration/lsp.test.ts
Somewhere in the refactor the await to wait for the server to finish
running was lost. This adds it back in. Thankfully the tests still pass
but now we ensure they will continue to test the to correct behavior.
> fix: adds important await to integration tests

- integration/lsp.test.ts
- src/wasm.rs
These functions accidentally got removed during the LSP refactor of the
WASM API. We now have integration tests to assert they are packaged in
the module.
> fix: readds parse and format_from_js_file functions

- release.sh
Prior to this change all releases would be considered a patch release.
This did not allow for following semver. Now you can specify the type of
release and control how the version is bumped.
> chore: add ability to specify version bump increment

- Cargo.lock
- Cargo.toml
- src/completion.rs
- src/shared/mod.rs
- src/shared/signatures.rs
- src/stdlib.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/mod.rs
The ExportEnvironment now only exposes references to MonoTypes this
change updates the code to be able to use those references without the
need to clone.
> fix: update to Flux master for ExportEnvironment changes

- integration/lsp.test.ts
- src/convert.rs
- src/server.rs
With this change we now publish diagnostics for Flux files based on the
results of analysis.
This change depends on two other changes:
~https://github.com/silvanshade/lspower/pull/20~
https://github.com/influxdata/flux/pull/4314 (Merged)
Based on ~https://github.com/influxdata/flux-lsp/pull/357~ and https://github.com/influxdata/flux-lsp/pull/356 (Merged)
~#357 is not required and if it gets delayed we can make that change later~
Update: Rebased the change to not require #357 to be merged.
> feat: add ability to publish diagnostics

- src/completion.rs
- src/stdlib.rs
This patch manually ports the work in #330, as the conflicts that
occurred there were too much to easily rework.
> refactor: refactor some low-hanging memory-use fruit

- src/completion.rs
- src/server.rs
- src/shared/mod.rs
- src/visitors/ast.rs
Additionally this change removes a few places where we parsed the same
contents multiple times in order access the AST
> refactor: cleanup completion code to not clone the contents

- Readme.md
- src/server.rs
With this change the server now supports the
textDocument/documentHighlight feature. The implementation is to report
all references of the identifier at the position.
> feat: add documentHighlight support

- Cargo.lock
- Cargo.toml
- src/completion.rs
- src/lib.rs
- src/server.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols.rs
These are no longer necessary after I refactored the `Visitor`  trait a while back to take `&mut self`
> refactor: Remove unnecessary Rc<RefCell<_>> wrappers

- Cargo.lock
- Cargo.toml
- src/completion.rs
- src/server.rs
For code like this
```flux
import "sampledata"
sampledata
```
Completing on `sampledata` would insert
`import sampledata2 "sampledata"` before completing the code to
```flux
import sampledata2 "sampledata"
import "sampledata"
sampledata2
```
Which is rather redundant when the package is already imported.
> fix: Don't inject duplicate package imports

- src/server.rs
This feels a bit hacky and I thought about just searching the returned `Node` path for the first `Node` for which `type_of()` returns a type, however that may return spurious hover results when just hovering over whitespace etc so I chose to be explicit instead.
> feat: Provide hover information on function parameters and assignments

- src/server.rs
In a situation where the flux document fails to type check, requesting
completions would lead to an RPC error.
~~Clients like the one used in the `com.github.gtache.lsp` will crash when they
encounter an RPC error, while the JS-based clients such as vscode and
the web UI seem to ignore them.~~
From a practical standpoint, it seems as though returning "no items" is
roughly equivalent to ignoring the error. The client will get no
completion information either way.
**Update:** after switching to a new LSP client API and finding similar breakage, and remarks from Markus in the standup today about "[RPC Errors] really signalling the client to close," I came back and tried to make this PR more comprehensive.
The gist here is to try and separate _programmer error_ (client and server) problems …
> refactor: give None when invalid flux source means a meaningful response body can't be built

- .circleci/config.yml
`wasm-build` already added this, to great results. I guess the resource
class didn't get added when `wasm-test` got added.
> test: use a large resource class on wasm-test

- src/completion.rs
- src/server.rs
- src/stdlib.rs
- src/visitors/ast.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/functions.rs
No longer necessary since visitors always take `&mut self` now
Based on #375
> refactor: Remove some redundant code/cloning

- Cargo.lock
- Cargo.toml
- src/server.rs
Switched to `BTreeSet` so that the display of want/got have consistent ordering in the assert
> feat: Update to flux 0.149.0

- Cargo.lock
- Cargo.toml
- src/server.rs
- src/visitors/semantic/mod.rs
With `Symbol` now implementing reference equality we can now easily determine whether two identifiers in the semantic graph refer to the same thing. Fixes one bug with `find references` and simplifies `goto definition` by comparing `Symbol == Symbol` instead of `String == String`
> feat: Distinguish references using Symbol's refernce equality

- rust-toolchain.toml
With
[CVE-2022-21658](https://blog.rust-lang.org/2022/01/20/cve-2022-21658.html),
rust 1.58 is no longer safe. This patch updates to use 1.58.1
> fix: update to rust 1.58.1

- wasm-build.sh
`wasm-build.sh` had a bug in it where it was producing dev binaries for
the final wasm builds, as well as including `console_log`, which more
than doubles the wasm binary size. This patch changes the release
process to produce a release binary without `console_log`.
> fix: don't produce dev binaries as final builds

- release.sh
I've been using `GITHUB_TOKEN` as an environment variable for my `hub`
authentication, and this `hub` auth verification breaks in my use case.
This patch makes the release script allow that environment variable.
> fix: allow env variable GITHUB_TOKEN in release

- src/bin/flux-lsp.rs
- src/lib.rs
- src/server.rs
- src/wasm.rs
`LspServerBuilder` was meant to abstract away a bunch of options that we
ported over from the previous lsp implementation. Slowly, those options
have been phased out. The last option left was about disabling folding,
which was odd, because the client should signal whether it supports
folding or not, so there's no need to flip that off and on.
This patch removes the `LspServerBuilder` entirely and just uses the
`LspServer::new` function directly.
> feat: remove LspServerBuilder

- src/server.rs
- src/visitors/ast.rs
This patch implements `textDocument/semanticTokens/full`. The work here
is mostly in converting ast graph into the lsp's semantic token
data structure. There isn't a 1:1 conversion, and there are a handful of
things that aren't highlighted, but it's a good start. This enables supported
clients to have syntax highlighting with minimal efforts.
Fixes #373
> feat: implement semantic_tokens_full

- src/completion.rs
- src/server.rs
The completion code we have was brought over from the old lsp, and has
some non-idiomatic things in it. It's a bit tangled, but I was trying to
fix some issues in the completion code and find some way to express the
completion code better, and this patch is what came out. It simplifies
things a bit, but isn't at all a final solution. Rather, it's a refactor
of code that should continue to be refactored.
> refactor: don't use Result if the Err never matters

- src/completion.rs
- src/server.rs
- src/visitors/ast.rs
- src/visitors/semantic/mod.rs
Thought this would be enough to fix #391 but it seems to take some more changes, still this at least
fixes `hover` (and probably some other LSP methods)
> fix: Provide hover information (and more) in the face of type errors

- src/visitors/ast.rs
- src/wasm.rs
`rust-analyzer` seemed to not like the wasm tests doing some things we
normally want clippy to catch. However, in tests, those clippy lints
shouldn't matter. For some reason, these lints weren't being caught
previously.
Additionally, there was a rogue `println` that got merged and would gum
up test output when running `cargo test -- --nocapture`.
> chore: fix issue detected in rust-analyzer

- src/completion.rs
- src/server.rs
This patch removes some dead code that had been ignored via clippy
previously. Additionally, it found one ignore statement that was
unnecessary.
> chore: remove dead code

- src/completion.rs
- src/lib.rs
- src/lsp.rs
- src/server.rs
- src/visitors/semantic/mod.rs
This patch adds support for the code actions capabilities. The only code
action currently supported is importing a package if an unknown
identifier matches a package that can be imported.
This functionality was then removed from the package code completion
logic, as it wasn't working anyway (it creates broken flux in the web
ui).
Fixes #393
> feat: add support for code actions

- src/server/mod.rs
- src/server/store.rs
- src/server/tests.rs
- src/server/types.rs
This patch adds a new `Store` type that handles the internals of the
data store and hides the actual in-memory representation. Additionally,
it _changes_ the in-memory representation a bit to make multi-file
package support just a bit easier. The order of the patches may help in
review, if the final patch is a bit too much.
This patch is the initial groundwork for handling multi-file package
support. The _actual_ implementation of multi-file package support
should really show up as its own patch, as it has the potential to cause
issues.
> feat: do initial groundwork for multi-file package support

- src/completion.rs
- src/server/mod.rs
- src/shared.rs
- src/stdlib.rs
- src/visitors/semantic/mod.rs
Refactorings I have done so far trying to understand what is needed for #392 . The only big thing is the first commit which starts caching for the semantic graph so we do not have to re-compile it on every LSP call (adding in https://github.com/salsa-rs/salsa might be nice here to make invalidations automatic, though it is a large/complex dependency).
All commits should be orthogonal and could be reviewed one by one.
> refactor: Remove unused code

- src/lsp.rs
The fields of `Position` is ordered as line -> column so we can just use contains here
> fix: Correct position in range for same line positions

- src/completion.rs
- src/server/mod.rs
- src/server/tests.rs
- src/shared.rs
- src/wasm.rs
Removes some duplicated semantic graph parsing and removes the completion specific semantic graph parsing (I don't understand what they were going for with the `_removed` suffix :S ) . Also some other smaller refactorings so reviewing commit by commit may be helpful.
> refactor: Pass in the semantic graph to completion instead of compiling from source

- src/lib.rs
This patch adds clippy lint rules to prevent `println!` and `eprintln!`
calls. It doesn't truly catch all issues printing to `stdout`/`stderr`,
but it would have caught some earlier invocations of `println!` left in
after debugging.
> fix: add clippy rules to prevent print macros

- src/completion.rs
- src/server/mod.rs
- src/server/tests.rs
- src/visitors/ast.rs
The completion code is very complicated compared to what it actually does (or at least compared to what we test it for). This removes special casing around how the completion is triggered (trigger character vs invoked) and which node/position we determine that we need to run completion on. Thanks to this it fixes #392 .
Since this is a rewrite of part of the completion this may change or lose completion in some instances but it should be easier to add those back later rather than trying to mold the existing code into something better (and we would add tests as well then, so we know when behavior is changed).
> fix: Complete function args in more contexts

- .circleci/config.yml
- Cargo.toml
- src/lib.rs
- src/wasm.rs
This patch removes strict mode by default. In general, I think having a
strict mode is good, and I think that CI should enforce something akin
to strict mode, but I realize now that there is plenty of reason for
that not to get in the way of tinkering during dev. I left it for so
long because go tends to have similar expectations, e.g. unused
variables won't compile, but I never liked that behavior and the man in
the mirror asserted the same things in rust.
> chore: disable strict mode by default

- src/completion.rs
- src/server/tests.rs
- src/shared.rs
- src/visitors/semantic/completion.rs
Changed the test to use `expect_test`, allowing it to easily test against the whole of the completion output
> feat: Display the type of a parameter during completion

- release.sh
This patch checks the ci state of HEAD before doing the release.
Additionally, it fixes the changelog calculation for release info to
work better than it did previously.
> chore: update release script

- src/server/mod.rs
- src/server/store.rs
- src/server/tests.rs
- src/visitors/semantic/mod.rs
This patch adds support for multi-file semantic packages. This allows a
user have two separate files open, and reference variables from file in
the package from the other.
Closes #405
> feat: add support for multi-file semantic packages

- src/completion.rs
- src/server/tests.rs
Updated a test to mostly make it more general. We get a quite weird parse here as `x` and `= 1`.
gets parsed as properties of the call expression but this at least fixes the completion for this case. (The parse itself will break completion done elsewhere however.
cc #392
> fix: Complete function arguments when it is followed by statements

- integration/lsp.test.ts
- src/server/mod.rs
- src/server/tests.rs
This patch fixes an issue where diagnostics were attempted before the
file is saved in the store, so no files are found to create a package.
This probably had a number of follow-on bugs, but the first issue
noticed was that diagnostics were not showing up.
Additionally, the signature of `compute_diagnostics` was updated. It was
left the way it was before just for patch brevity, but that was probably
a mistake.
Closes #428
> fix: publish diagnostics on open

- Cargo.lock
- Cargo.toml
- benches/server.rs
- integration/lsp.test.ts
- integration/package.json
- src/bin/flux-lsp.rs
- src/completion.rs
- src/lsp.rs
- src/server/mod.rs
- src/server/store.rs
- src/server/tests.rs
- src/server/types.rs
- src/shared.rs
- src/visitors/ast.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/functions.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols.rs
- src/wasm.rs
`lspower` has been merged back into `tower-lsp` and is now deprecated.
This patch switches the dependency and updates the code to reflect the
new dependency.
Fixes #430
> feat: switch to tower-lsp

- Dockerfile
This patch adds `wabt` and `binaryen` to the docker image used to build
the wasm binaries. These two packages provide some wasm tools we'll use
in the future to shrink the wasm binary size.
Additionally, the debian version was updated (the stable debian is now
bullseye) and the node version was updated to 16, as 12 goes EOL on
Apr 30, 2022, and 16 is the version used in vsflux.
> feat: add wasm tools to docker image

- Cargo.lock
- Cargo.toml
- src/bin/flux-lsp.rs
This patch updates outdated dependencies in `flux-lsp`.
> chore: update outdated dependencies

- .gitattributes
- Cargo.lock
- Cargo.toml
- src/lib.rs
- src/wasm.rs
- wasm-build.sh
This patch does a number of things, all in the name of shrinking the
final wasm binary size. The first three are introducing features, two to
change the logging to optional, and one to use a smaller allocator (by
10k).
Additionally, it introduces using some tools to shrink the binary
further by removing more sections that are unneeded. These are used in
`wasm-build.sh`.
Fixes #432
> feat: shrink the wasm

- update-downstream.sh
This script automates some follow up work that needs to be done every
time there is a flux-lsp release.
> chore: add update-downstream.sh

- .github/PULL_REQUEST_TEMPLATE.md
Every time I'm out in the field, I stumble into [this fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence).
I looked in the git history to see why it exists, and it was added by
default when the license was added. There has never been an outside
contributor to `flux-lsp` (all contributors were, at some point,
employees/contractors of InfluxData). The only time I encounter it is to
delete it, and I don't think it provides value that can, at this stage
in the maturity of the project, be conveyed better.
At this point, I feel comfortable understanding this fence, and feel its
removal is appropriate.
> chore: remove pr template

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- src/bin/flux-lsp.rs
- src/lib.rs
- wasm-build.sh
This patch separates the final build artifacts into two separate
features. The resulting changes to `Cargo.toml` reduced the final wasm
binary size by 350k, but the benefit to this work has been the explicit
separation between the two build artifacts and their needs.
The flux-lsp is really two separate products: a `flux-lsp` command-line
binary, and a wasm library consumed by a browser. Because of that, there
can be some really awkward interactions for how the source reads. This
work seems important to do now, before we start getting more complex on
the wasm side.
> feat: separate final build artifact results into features

- src/completion.rs
- src/server/mod.rs
- src/server/store.rs
- src/server/tests.rs
- src/stdlib.rs
- src/wasm.rs
This all started as I was digging into fixing another bug. As I was diving
through the code, I started realizing that there were a lot of things captured
in comments that should be issues, and other things that no longer applied, and
it just kind of unrolled into a bunch of nits. `XXX` and `TODO` comments were
either verified to no longer be needed or converted into an issue.
While I was there, I then added the version information from initialization,
which is what I originally needed a branch for, so I could verify that we were,
indeed, running the version of flux-lsp that I needed.
Each individual commit should provide all the context needed. Apologies for
such a wildly out-of-context patch. It just sort of...happened.
> chore: small nits and changes

- src/server/store.rs
- src/wasm.rs
`RwLock` is like `Mutex` except that it allows multiple read references
but still only one write reference maximum. Most lsp operations only
need a read reference, so while I don't think there are _currently_
performance bottlenecks for a `Mutex`, `RwLock` does send a different
message in its use, which is more applicable in this case.
> fix: use RwLock instead of Mutex

- src/server/mod.rs
- src/server/tests.rs
Prior to this patch, there was a bug when, should an error exist
in another file in the package, that diagnostic was reported on _all_
files in the package. This patch fixes that issue to only report errors
on the trigger file, e.g. the file that sent the
`didOpen`/`didChange`/`didSave` event.
Fixes #456
> fix: only show diagnostics relating to the the trigger file

- Cargo.lock
- Cargo.toml
- benches/server.rs
- integration/lsp.test.ts
- src/bin/flux-lsp.rs
- src/completion.rs
- src/lib.rs
- src/lsp.rs
- src/server/mod.rs
- src/server/store.rs
- src/server/tests.rs
- src/server/types.rs
- src/shared.rs
- src/visitors/ast.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/functions.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols.rs
- src/wasm.rs
There's a showstopper issue related to `tower-lsp` and our `onMessage`
handler code in the wasm export. This patch reverses that update so that
we aren't blocked with continuing feature work while we figure out what
we're missing there.
> fix: downgrade back to lspower

- src/diagnostics.rs
- src/lib.rs
- src/server/mod.rs
- src/server/tests.rs
- src/visitors/semantic/lint.rs
- src/visitors/semantic/mod.rs
This patch adds some new linting architecture into the diagnostic mechanisms of
the lsp. It also brings with it two small lints, both showing information about
using `contrib` and `experimental`.
Fixes #461
> feat: add linting infrastructure and provide hints about contrib/experimental

- src/wasm.rs
When calling `run`, the server is consumed and control is, effectively,
lost. When trying to attach an `onMessage` handler after `run`, the
handler can't attach; the `Lsp.processor` is `None` at that point. This
patch causes the wasm to panic explicitly when `onMessage` is called on
a running server.
Fixes #462
> fix: panic when onMessage is called after run

- src/server/mod.rs
- src/visitors/ast.rs
I were looking into some weirdness in the syntax highlighting which lead me to looking at the semantic tokens implementation where I noticed this comment. So I made a small refactor to remove the need for it.
(Turns out neovim doesn't actually support semantic tokens yet anyway so the problem was in the normal syntax file. I am not sure semantic tokens are actually enabled on the server side either? It might need define `full: true` in the configuration?)
> refactor: Make adding new semantic tokens less brittle

- src/diagnostics.rs
- src/server/mod.rs
- src/server/store.rs
- src/server/tests.rs
- src/visitors/semantic/lint.rs
- src/visitors/semantic/mod.rs
This patch introduces new lints for assigning variables to `v`, `params` and
`tasks`. We want to discourage users from using these three names as variable
(regardless of scope), because the InfluxDB ecosystem may specify these at
runtime and break the script. When influxdata/flux#4834 is addressed, we will
still want these lints, though we'll likely then downgrade them to "hints"
as opposed to the "warning" levels they are now (they can potentially break
your script in non-obvious ways currently).
As part of this work, we needed to (properly) address an issue we previously
handled in the diagnostics where an error from a file would show as an error in
another file from the same package. While the errors were handled properly, a
test broke that showed that the lints were reporting …
> feat: publish warnings for use of `v`, `params`, and `tasks`

- Cargo.lock
- Cargo.toml
- src/server/mod.rs
- src/server/store.rs
- src/server/tests.rs
- src/server/transform.rs
- src/server/types.rs
This patch adds in the initial work to inject a tag value filter to
a query.
Fixes #485
> feat: add ability to inject a tag value filter

- src/server/mod.rs
- src/server/transform.rs
This patch adds support for injecting a `filter` call to narrow a query
by the existence of a tag. For instance, you could turn the following:
from(bucket: "myBucket")
...into...
from(bucket: "myBucket")
|> filter(fn: (r) => exists r.myTag)
Fixes #484
> feat: add support for injecting a tag key filter

- src/server/mod.rs
- src/server/transform.rs
This patch adds support for dynamically injecting a `_field` filter to a
query, so this:
from(bucket: "myBucket")
...becomes...
from(bucket: "myBucket")
|> filter(fn: (r) => r._field == "myField")
Fixes #483
> feat: add support for injecting field filtering

- src/server/mod.rs
- src/server/transform.rs
This patch adds support for injecting measurement filters, so the
following query
from(bucket: "myBucket")
...becomes...
from(bucket: "myBucket")
Fixes #482
> feat: support for injecting measurement filter

- .cargo/config
- src/bin/flux-lsp.rs
- src/lib.rs
- src/server/mod.rs
- src/server/transform.rs
This patch adds support for finding or creating the `from` call when
injecting filter functions. It does not add the `range` pipe expression,
as we're at a turning point where we need to find a better way to
express new AST nodes and transformations. Otherwise, the patch might be
prohibitively large at this time.
Additionally, fix the lint rules for `clippy::print_stdout` and
`clippy::print_stderr`. Since they were macros, they were being
evaluated too late to be caught. They are now specified as compiler
flags.
> feat: find or create the `from` call

- src/server/commands.rs
This PR fixed a bug where lsp command was mismatched
> fix: match injectFieldFilter with corresponding command

- Readme.md
This PR updates the test command in Readme file. Since there is not a Makefile and rust already has its own package manager `cargo` for testing, so it makes more sense to change the command to `cargo test`
> chore: update Readme for test command

- src/server/transform.rs
This patch adds a `|> range` to a previously unbounded `from` call, a call
that will never complete in cloud because unbounded queries aren't allowed.
The `range` specifies `start`/`stop` as `params.timeRangeStart`/`params.timeRangeStop`.
> feat: add a range pipe to the unbounded from

- src/server/mod.rs
- src/visitors/ast.rs
- src/visitors/semantic/lint.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols.rs
This patch goes back to using the features tagged as "lsp" from libflux,
as the library compatibility issues have been resolved.
> fix: revert back to using the lsp features from libflux

- src/completion.rs
- src/server/mod.rs
- src/server/tests.rs
- src/stdlib.rs
- src/visitors/ast.rs
First things first: this patch is probably bigger than is normally appropriate
for a code review. In this case, it was unavoidable, as every time we tried to
make small changes to make this code better, it just kinda made things worse
or the attempt was abandoned. The layers and layers and layers of indirection
are just too tangled up to not make this change atomically. Even in this state,
we still didn't get all the indirection, but we've narrowed it down to a single
narrow code path.
You can tell this is a refactor because it doesn't touch any existing tests. I
found a test I think is outright wrong, and I found functionality that we
likely don't want, and I added a test, but this code doesn't change the actual
experience of this code. It's complex enough without adding features or …
> refactor: rewrite/move completion code

- src/completion.rs
- src/diagnostics.rs
- src/lib.rs
- src/server/mod.rs
This patch introduces a set of macros that do a very common thing: wrap
the ast/semantic graph in a walk node, and then walk that node with a
visitor.
> refactor: create semantic/ast walk macros

- rust-toolchain.toml
- src/server/mod.rs
Additionally, there was a new `clippy` lint introduced in 1.61 that needed to
be addressed.
> chore: upgrade the version of rust

- .circleci/config.yml
- Cargo.toml
- src/wasm.rs
Months ago, we started thinking about an API for working with flux AST
in javascript. That work then got de-prioritized for other work. This
API is still pretty experimental, and it shouldn't ship in the default
wasm binary for now.
BREAKING CHANGE: The exported `Flux` object in the wasm is no longer
available.
> chore: hide lang features behind a feature flag

- src/completion.rs
- src/lang.rs
- src/server/mod.rs
- src/server/store.rs
- src/visitors/semantic/symbols.rs
This patch is the result of an audit of all the places where mutable
values are used, and removes them where possible. In some cases, it
wasn't realistic to remove them, either because it would make the code
much less readable, or because that change would be big enough to
warrant its own patch.
> refactor: audit and remove unnecessary mutability

- wasm-build.sh
While we were trying to shrink the size of the wasm, we removed some
infrastructure for learning about errors in the lsp. One of those is an
installed hook for catching panics and logging them (with traceback
information) to the console. The idea was that we were delivering a
binary, and we (usually) wouldn't leave debug symbols in a shipped
artifact. That decision wasn't correct. This patch re-instates that
panic hook by flipping that flag on in the build script.
Aside: While I don't think we should be careless with the size of the shipped
wasm binary, I don't believe we need to be super sensitive to it, and we
should especially not make compromises to delivering a rock solid binary.
> feat: enable console_error_panic_hook by default

- src/lang.rs
- src/server/mod.rs
- src/server/tests.rs
- src/visitors/semantic/mod.rs
This is the final refactor patch that helped me understand the full interaction
here and what's going wrong with my current feature work. This patch removes
more indirection from functions that exist to only be called once, as well
`for` loops that required mutability and mutable parameters.
This patch seems scatter-brained, and it's true, to an extent. This area of the
code evolved in a kinda scatter-brained way, and my brain was also fried while
trying to figure this out. I'm confident, at this point, that I know the path
forward, and would like to take that path forward without littering it up with
the changes from this patch.
> refactor: more lang indirection and mutability removal

- .circleci/config.yml
- .gitignore
- integration/package.json
- publish.sh
- wasm-build.sh
The big difference here is that we use native WebAssembly memory model,
so browser tooling can be used to inspect the segfault.
> fix: use web instead of bundle type for wasm

- src/completion.rs
- src/lang.rs
- src/server/mod.rs
- src/server/tests.rs
- src/visitors/semantic/completion.rs
- src/visitors/semantic/functions.rs
- src/visitors/semantic/mod.rs
This patch introduces an API for querying the flux stdlib and prelude/universe.
Having a standard way to do this will cut down on the repeated allocations
that come about from each call point getting its own copy of the stdlib, using
it for a very narrow case, and then throwing it away (likely with more call
points doing the same down the road).
Architecturally, this starts to provide an abstraction to the flux stdlib for
the cases where a low-level api probably isn't needed, e.g. we need the names
of packages, but not the package itself. These new apis would hide those
implementations, and handle some logic between flux<->lsp data structures.
This is the last of the refactoring needed to clean up the path for making
function completion (and injection) work without much accompanying …
> refactor: Provide interfaces for querying flux stdlib

- publish.sh
The path to where the wasm artifacts are built changed recently, and
while the `publish.sh` script was updated, there were issues in it that
meant that we couldn't successfully release. This patch fixes those
issues (theoretically, as it can't be fully tested).
> fix: address release issues in publish script

- .circleci/config.yml
By default, tags don't have workflow jobs enabled. This path
specifically opts in for those workflow jobs, so that the publish
job's requirements can be met.
> fix: opt in for the workflow steps on tags

- src/completion.rs
- src/server/tests.rs
This patch adds real snippet support to function parameter completion.
This means that one could potentially tab through each parameter in the
parameter list and add their associated values.
This patch is hilariously small and direct now that all the refactoring is
done.
Fixes #435
Fixes #431
> feat: add function snippet syntax

- wasm-build.sh
Earlier this week, we discovered that some time ago, the `browser`
type had disappeared from `wasm-pack` and was replaced with `bundler`
and `web`. Specifying `-t browser` fell through to using the `bundler`
type. In an attempt to possibly make debugging the wasm a little easier,
we switched to using `-t web`, which uses `WebAssembly` for memory
management instead of using raw memory management.
Unfortunately, this new format broke the InfluxDB ui build. Webpack in
the UI will likely need some help understanding the `web` type, if
that's a direction we'd like to go. For now, we'll support just the
bundler.
Fixes #540
> fix: revert wasm-pack to bundler type

- Cargo.lock
- Cargo.toml
- src/diagnostics.rs
- src/server/mod.rs
This patch adds a diagnostic check for usage of an identifier that isn't
using camelCase. This came about from a conversation with the flux team
where everyone felt good about preferring camelCase.
Fixes #537
> feat: introduce a lint rule to prefer camelCase

- src/completion.rs
- src/server/tests.rs
This patch wraps completion snippets for function parameters that could
be strings in double quotes.
> feat: wrap completion snippets string types

- src/server/transform.rs
This patch is a first (experimental) attempt at creating a macro api for
constructing asts.
> refactor: use macros to build the ast

- src/composition.rs
- src/lib.rs
This patch implements the Composition feature as far as initialization and
adding of a measurement. It includes the constraints for not being able to add
multiple measurements.
> feat: implement the initial composition

- src/composition.rs
One of the tenets of composition is that we aren't going to apply a filter that
already exists, e.g. adding a field that we've already added. This means that
we'll have to check to make sure that those items don't already exist. This
patch mutates our query composition visitor such that it analyzes our
composition statement for the various filters that we apply.
Additionally, its test should serve as an example for what a more complex
composition query would look like.
> feat: introduce a composition query analyzer

- src/composition.rs
* https://github.com/influxdata/flux-lsp/pull/554
* **THIS PR**
* https://github.com/influxdata/flux-lsp/pull/556
* https://github.com/influxdata/flux-lsp/pull/557
6. `add_tag()`
* https://github.com/influxdata/flux-lsp/pull/558
Have macro `filter!` handle multiple predicate statements, all with the same logical operator. Use macros for the compile time AST construction, sandwiched around a runtime fn `logical_expr()` which handles the runtime determined length of the values array.
> feat: have macro filter! handle multiple predicate statements

- src/composition.rs
* https://github.com/influxdata/flux-lsp/pull/554
* https://github.com/influxdata/flux-lsp/pull/555
* **THIS PR**
* https://github.com/influxdata/flux-lsp/pull/557
6. `add_tag()`
* https://github.com/influxdata/flux-lsp/pull/558
Ability to add a field filter to a composition. Also allow adding the next field to the same filter.
> feat: add_field() for composition

- src/composition.rs
* https://github.com/influxdata/flux-lsp/pull/554
* https://github.com/influxdata/flux-lsp/pull/555
* https://github.com/influxdata/flux-lsp/pull/556
* https://github.com/influxdata/flux-lsp/pull/557
6. `add_tag()`
* **THIS PR**
Ability to add a tag filter to a composition.
Use same calls to `filter!` macro, which matches different for the `exists x` versus `r.x == y`.
> feat: add_tag() for composition

- src/composition.rs
- src/server/mod.rs
Part of #549.
Implemented in accordance with the spec defined here:
https://github.com/influxdata/flux-lsp/pull/547
* the composition submodule code is already in existence.
* in this PR:
> feat: wire composition add_field() and remove_field() into lsp server

- src/composition.rs
- src/server/mod.rs
Part of #549.
Implemented in accordance with the spec defined here:
https://github.com/influxdata/flux-lsp/pull/547
* the composition submodule code is already in existence.
* in this PR:
> feat: wire composition add_tag() and remove_tag() into LspServer

- src/composition.rs
- src/server/commands.rs
- src/server/mod.rs
Part of #549.
Implemented in accordance with the spec defined here:
https://github.com/influxdata/flux-lsp/pull/547
* the composition submodule code is already in existence.
* in this PR:
> feat: add_tag_value() and remove_tag_value() wired into LspServer

- src/composition.rs
- src/server/mod.rs
1. create a schema composition. Make it longer (more tags etc).
2. re-init the composition by selecting a new measurement.
3. the replacement applyEdit is only for the first 3-4 lines. So we get half old block, half new block.
Vid:
https://user-images.githubusercontent.com/10232835/186808056-058ace8d-8ab4-4311-92be-cec05350171a.mp4
> fix: applyEdit replacement text size, upon composition initialize

- src/server/mod.rs
Closes #574 
And applies the fix for all composition methods, not just the initialize.
> fix(574): always use the replacement position for the applyEdit

- src/composition.rs
- src/server/commands.rs
- src/server/mod.rs
This patch allows initialize to add extra filters atomically on
initialization. This means that users who continue to tack on state
after the composition is turned off will be able to see those changes
when composition is turned back on, as the client has the ability to
specify them all in a single request.
> feat: allow initialize to add extra filters

- src/composition.rs
- src/server/mod.rs
Closes #576 
Closes https://github.com/influxdata/ui/issues/5634
It was creating duplicated code in the UI editor. ApplyEdit was inserting both the composition, and code existing in the rest of the file (outside the block).
With this change, we can hopefully preserve the flux code outside of the block...which also means copy/paste of previous compositions (to make subqueries) in the same flux script.
> fix(576): new_text in composition applyEdit should only be the composition string. Not the entire file string.

- src/server/mod.rs
Closes #578 
the line_col library does 1 indexing for lines and chars, whereas the monaco-editor range (per LSP spec) does zero-based lines and chars.
> fix(578): fix off-by-1 error. Handle zero-based indexing in LSP range.

- src/server/mod.rs
- src/server/tests.rs
Thought we might have gotten this for free with https://github.com/influxdata/flux/pull/4957 but I ran into this again today. Previously this would complete the identifier like any other identifier, now it will only select properties of the object.
> fix: Complete empty properties on member expressions

- src/server/mod.rs
- src/server/tests.rs
Picking out the constraints from the parent variable binding seems to work in this simple case but it may break down in more complicated examples. It doesn't seem like a great way to do it either but I am not sure how else we can without changes to the semantic graph.
> feat: Display the type constraints when hovering over something

- Cargo.lock
- Cargo.toml
- src/server/commands.rs
- src/server/mod.rs
This patch adds a dependency that allows us to iterate over an enum, and
applies it to the `LspServerCommand` enum, and then iterates over them
in the initialization of the server.
Fixes #587
> fix: provide all lsp execute commands in initialization

- src/server/mod.rs
- src/server/tests.rs
In more lsp initialization auditing, we don't signal support for
`textDocument/didSave`. Our `textDocumentSync` capabilities used the
"kind" path rather than the specific options. This patch switches to
using the options, but doesn't use the `textDocument/didSave` event
because it would only do the same as the `textDocument/didChange` event,
which we already handle. This way, we aren't locking the store to set
the same value already set in `textDocument/didChange`.
> chore: remove didSave

- src/composition.rs
Close influxdata/ui#5949
This PR updates the AST for multi tag values in the following rules:
* If adding a tag value where the tag key already exists in the flux file, use `or`.
* If adding a tag value with a new tag key, append a new `filter(...)` function. This function as implicit `and`.
> chore: support multi tag value selection

- Cargo.lock
- Cargo.toml
- src/composition.rs
- src/lib.rs
- src/server/mod.rs
- src/server/tests.rs
- src/server/types.rs
This is a big patch, and with reason. Previously, composition wasn't stateful,
so the composition statement was re-initialized on every subsequent
composition-related command. This meant we had to have some way of finding it
all the time. This patch makes the composition part of the lsp server state,
so it lives along with the contents of the file. This means that composition
can survive unrelated edits to the file, can take manual changes to the
composition statement itself, etc.
The tests all had to be re-architected, because composition changed so
dramatically. In this case, the tests all live around the `Composition` struct
itself and don't test any more of the internal details. When the changes
started coming, and the internal details changed so much, it made it hard to
keep them …
> feat: use stateful composition

- rust-toolchain.toml
- src/server/mod.rs
New rust is out. Use new rust. Fix new clippy lints.
> chore: update to rust 1.65

- Cargo.lock
- Cargo.toml
- src/lib.rs
Closes #613 
Per notice of memory leak risk and unmaintained lib (see links in issue^^), replacing wee_alloc with the [recommended dlmalloc](https://rustsec.org/advisories/RUSTSEC-2022-0054.html). 
Difference is ~2.5 kB wasm size from before (left), versus after (right), using build `BUILD_MODE=release AR=llvm-ar ./wasm-build.sh`:
> chore(613): replace unmaintained wee_alloc with dlmalloc

- src/composition.rs
- src/server/commands.rs
- src/server/mod.rs
- src/server/tests.rs
Part of https://github.com/influxdata/ui/issues/6334
Closes https://github.com/influxdata/flux-lsp/issues/615
Note: this is part of a chain of PRs, which should be merged together. These PRs will handle the [3 basic tasks outlined here in this Epic](https://github.com/influxdata/ui/issues/6334).
This PR is the `FIRST_TASK`, which has both UI and flux-lsp changes. The ui changes [are here](https://github.com/influxdata/ui/pull/6344).
Closes #615  (`FIRST TASK` on the epic, lsp side changes).
That^^ issue ticket describes in detail, on why these changes were required. Also includes video evidence as each step, when finding all the bugs.
Broke out each commit, to correlate to a bug/issue listed in ticket 615:
* change to use `executeCommand/setMeasurement`
* two bugs found in the applyEdit …
> feat(615): basic composition coordination with UI

- src/composition.rs
- src/server/commands.rs
- src/server/mod.rs
Part of Epic https://github.com/influxdata/ui/issues/6334
Closes #609 — `fluxComposition/compositionEnded`
Closes #610 -- ` fluxComposition/compositionState`
Note: this is the last in a chain of PRs, which should be merged together. These PRs will handle the [3 basic tasks outlined here in this Epic](https://github.com/influxdata/ui/issues/6334).
This PR is the `THIRD_TASK`, which has both UI and flux-lsp changes. The ui changes are here.
Each commit details exactly which changes, and why. If summary, these are:
1. send a `window/showMessageRequest` with an array of ActionItem for the ui to consume. Spec [is here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#window_showMessageRequest).
2. switched to using a custom_notification, since the …
> feat(609/610/ui-6334): LSP notification sent to UI with ActionItems

- src/wasm/lsp.rs
Forgot to appropriately set the logging level to Info and higher.
(Was spamming the UI browser console with debug messages. lol)
Here is what the Info (and higher) looks like in the browser console:
> chore: update LspServer logging level to Info (not debug)

- Cargo.lock
- Cargo.toml
- integration/lsp.test.ts
- src/wasm.rs
- src/wasm/lsp.rs
- wasm-build.sh
Closes #618 
* wasm start now triggers logger setting at the wasm root (on load in browser). Confirmed will allow logging in LspServer and utils module.
* update test fixtures, to make more explicit what the `parse()` contract does.
* note: we are misusing `parse()` as a validation method in the UI. Which is wrong.
* expose an `is_valid_flux()` method which can be used for validation in the UI
The size of our wasm can impact network load times. With the changes made here, the release build has an increase in 25kB size.
> fix(618): handle remaining wasm panics, and expose is_valid_flux() API
