influxdata/flux-lsp

- src/utils.rs
> fix(flux-lsp): fixes windows file path issue

- Readme.md
A tiny bit of cleanup to the readme.
> chore(readme): add links

- .circleci/config.yml
- Cargo.lock
- Cargo.toml
- Makefile
- src/cache/mod.rs
- src/handler.rs
- src/handlers/document_change.rs
- src/handlers/document_close.rs
- src/handlers/document_open.rs
- src/handlers/document_save.rs
- src/handlers/folding.rs
- src/handlers/mod.rs
- src/lib.rs
- src/protocol/properties.rs
- src/protocol/requests.rs
- src/utils.rs
- src/visitors/semantic/utils.rs
- tests/handlers.rs
> Cache changes

- src/main.rs
bump up the version of flux-lsp master for the next releae, so IDE can detect and pull the latest version
> chore(src): update the version for next release

- Readme.md
> add some badges

- .gitignore
- Cargo.lock
- Cargo.toml
- Dockerfile
- build.sh
- publish.sh
- src/cache/mod.rs
- src/handler.rs
- src/handlers/document_change.rs
- src/handlers/document_close.rs
- src/handlers/document_open.rs
- src/handlers/document_save.rs
- src/handlers/mod.rs
- src/lib.rs
- src/shared/mod.rs
- src/utils.rs
- src/visitors/ast/mod.rs
- src/wasm/mod.rs
- tests/handlers.rs
- tests/wasm.rs
- wasm-build.sh
> feat(flux-lsp): track changes as internal state

- publish.sh
> chore(flux-lsp): update publish script to publish to public

- Cargo.lock
- Cargo.toml
- src/handler.rs
- src/handlers/document_symbol.rs
- src/handlers/mod.rs
- src/protocol/properties.rs
- src/protocol/requests.rs
- src/protocol/responses.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols/mod.rs
- tests/fixtures/simple.flux
- tests/handlers.rs
> feat(flux-lsp): respond to document symbol requests

- Readme.md
> Update install instructions

- Cargo.lock
- Cargo.toml
- build.sh
- src/stdlib/mod.rs
- src/visitors/semantic/utils.rs
- tests/handlers.rs
> Add builtins to completion

- src/handlers/completion.rs
- src/handlers/document_symbol.rs
- src/handlers/folding.rs
- src/handlers/goto_definition.rs
- src/handlers/mod.rs
- src/handlers/references.rs
- src/handlers/rename.rs
- src/protocol/properties.rs
- src/shared/mod.rs
- src/stdlib/mod.rs
- src/utils.rs
- src/visitors/ast/mod.rs
- src/visitors/semantic/mod.rs
- src/visitors/semantic/symbols/mod.rs
- src/visitors/semantic/utils.rs
- tests/fixtures/completion.flux
- tests/handlers.rs
- tests/wasm.rs
> Completion of user defined variables

- src/stdlib/mod.rs
- tests/handlers.rs
> Fixes builtin duplications

- src/stdlib/mod.rs
- src/visitors/semantic/completion/mod.rs
- tests/fixtures/completion.flux
- tests/handlers.rs
Introduces user readable generic types
Closes #90
> Completion for user defined functions

- .circleci/config.yml
Closes https://github.com/influxdata/flux-lsp/issues/83
Describe your proposed changes here.
add rustfmt ci
> feat(ci): add rustfmt

- .circleci/config.yml
sometimes nightly is not available, this pr will just use the old rustfmt
> fix(ci): revert to standard rustfmt

- Readme.md
I'm hoping to capture some of the ambiguity that came out of implementing this on the browser
> feat: adding more readme

- src/handlers/completion.rs
- src/wasm/mod.rs
> Add quotes around bucket completions

- Cargo.lock
- Cargo.toml
- src/stdlib/mod.rs
> Fix bucket snippet

- .gitignore
- src/handlers/completion.rs
- src/visitors/ast/mod.rs
- tests/fixtures/package_completion.flux
- tests/handlers.rs
- wasm-build.sh
> Use AST for ident finding for completion

- Cargo.lock
- Cargo.toml
- src/handlers/completion.rs
> Trigger completion fallback

- src/visitors/semantic/completion/mod.rs
> Add completion for object function members

- src/protocol/requests.rs
> Fixes naming of serialization fields for signature help

- Cargo.lock
- Cargo.toml
- src/handlers/completion.rs
- src/lib.rs
- src/macros/mod.rs
- src/visitors/ast/mod.rs
- src/visitors/semantic/mod.rs
- Trigger type from parsed flux
- Bucket for current function
> Add more context to completion

- Makefile
- src/handlers/completion.rs
- src/protocol/properties.rs
- src/shared/callbacks.rs
- src/visitors/ast/mod.rs
- src/wasm/mod.rs
- wasm-build.sh
- when used in logical == operation
- when a paramater for a function
> Add measurement completion

- src/handlers/document_formatting.rs
- src/handlers/mod.rs
- src/handlers/router.rs
- src/protocol/properties.rs
- src/protocol/requests.rs
- src/protocol/responses.rs
- tests/fixtures/formatting.flux
- tests/handlers.rs
> Add formatting support

- Cargo.lock
- Cargo.toml
- src/handlers/completion.rs
- src/handlers/document_symbol.rs
- src/shared/callbacks.rs
- src/visitors/semantic/utils.rs
- src/wasm/mod.rs
> Tag key completion

- src/handlers/completion.rs
- src/handlers/signature_help.rs
- src/stdlib/mod.rs
- src/visitors/semantic/completion/mod.rs
- src/visitors/semantic/utils.rs
- tests/handlers.rs
> Implement import completion

- src/handlers/completion.rs
- src/shared/mod.rs
- src/stdlib/mod.rs
- src/visitors/ast/mod.rs
- src/visitors/ast/package_finder.rs
- src/visitors/semantic/completion/mod.rs
- tests/handlers.rs
> Imports account for package clause

- Cargo.lock
- Cargo.toml
- src/cache/mod.rs
- src/handlers/document_save.rs
- src/handlers/mod.rs
- src/protocol/notifications.rs
- src/shared/mod.rs
- src/stdlib/mod.rs
- src/visitors/semantic/completion/mod.rs
- src/visitors/semantic/completion/results.rs
- src/visitors/semantic/completion/utils.rs
- tests/handlers.rs
> Package completions for aliased imports

- .circleci/config.yml
> Update deploy CI step

- Makefile
- wasm-build.sh
> fix(lsp): modify makefile and wasm-build.sh to be more automate-friendly

- Cargo.lock
- Cargo.toml
> build: upgrade to Flux v0.90.0

- Cargo.lock
- Cargo.toml
- tests/handlers.rs
> build(flux): Upgrade to Flux v0.94.0

- Cargo.toml
Change version from v0.5.21 to v0.5.22
> build: Increment version

- Cargo.lock
- Cargo.toml
- Change version from v0.5.27 to v0.5.28
- Upgrade Flux to v0.101.0
> build: Bump to v0.5.28

- Cargo.lock
- Cargo.toml
Change version from v0.5.30 to v0.5.31
> build: Bump to v0.5.31

- src/shared/mod.rs
- src/shared/structs.rs
- src/visitors/semantic/completion/mod.rs
> chore: Appease clippy

- Cargo.toml
Bump the lsp version and manually update flux version
> build: Release v0.5.49

- Cargo.toml
- src/bin/flux-lsp.rs
- src/lib.rs
- src/server.rs
This patch creates a rust-based cli for the lsp, based on the new
lspower based server.
> feat: rust-based cli

- src/server.rs
This patch implements `textDocument/didClose` in the new lsp server.
Additionally, it logs when a file is opened when already opened and
closed if not currently opened, as the protocol seemed ambiguous whether
that was allowed, but that information may be helpful.
Fixes #245
> feat: implement textDocument/didClose in new lsp server

- src/server.rs
This patch implements tho `textDocument/foldingRange` rpc call in the
lspower lsp server.
Closes #248
> feat: implement folding range

- src/handlers/document_symbol.rs
- src/server.rs
> feat: implement documentSymbol

- src/server.rs
This patch implements `textDocument/definition` in the new lspower
server.
Closes #249
> feat: implement gotoDefinition

- src/server.rs
This patch implements `textDocument/didSave` in lsp2.
Closes #246
> fix: implement textDocument/didSave in lsp2

- Readme.md
> docs: document the new way to install/use flux-lsp

- src/server.rs
The lsp server would panic when trying to `parse_and_analyze`
unparseable flux. This patch handles those parse errors and returns
a proper response.
Fixes #309
> fix: handle parse errors when resolving some requests

- src/wasm.rs
We can just catch all panics and return them as errors back up to WASM
> fix: Avoid crashing wasm on panics

- release.sh
I encountered two problems when running the release script:
1. My hub command did not have authentication setup, this cause the
script to fail after it had already pushed the release commit to
Github.
2. Because of the above failure the master branch was in a bad state and
I could not run the release script as Cargo.lock was out of sync with
Cargo.toml because of the version bump.
I didn't find a way to fix the second problem as it would need to be a
feature of "cargo bump". However I fixed the first problem which should avoid
the second problem entirely.
> chore: update release.sh to be more robust

- src/server.rs
With this change the hover response reports the type of the expression
at the position. There are still cases where we won't find an expression
at the cursor but for the most part this works well.
> feat: add hover response that reports expression type

- Readme.md
Re: https://github.com/neovim/nvim-lspconfig/pull/1583
> fix: update readme instructions for nvim-lspconfig

- Cargo.lock
- Cargo.toml
- src/completion.rs
- src/convert.rs
- src/server.rs
- src/stdlib.rs
- src/visitors/ast.rs
Rebased the branch I had prepared earlier on top of #374
Closes #374
> feat: Update to flux 0.148.0

- src/server.rs
- src/visitors/semantic/mod.rs
Another missing feature I noticed while using it.
> feat: Make goto_definition work on builtins

- src/server.rs
Noticed it didn't work in these places as well
> feat: Provide hover information on properties

- src/server/mod.rs
This patch just removes a few functions that were unneccessary, either because
they are a single, straightforward line of code, or because they were function
abstractions only ever called once. Most of this is carry over from the old,
hand rolled lsp, and this cleans the code up quite a bit.
> chore: remove some unneccessary abstractions

- Cargo.toml
- src/server/mod.rs
- src/server/tests.rs
This patch adds the state required to store the buckets in the workspace
state as a result of `workspace/didChangeConfiguration`.
> feat: store buckets in workspace state

- release.sh
- update-downstream.sh
This PR adds https authentication option for github when ssh doesn't work.
> chore: add https auth option for github

- Readme.md
See https://github.com/influxdata/flux-lsp/issues/511
> docs(readme): update install instructions

- src/server/mod.rs
- src/server/tests.rs
This patch removes the use of Cow, mostly as an experiment. This may or
may not be ultimately helpful, but currently chasing runtime borrow
issues.
> fix: remove use of Cow

- release.sh
The release script had some issues where it would generate an empty
changelog. I only really noticed when there were a small amount of
changes, but we were trimming off the most recent change thinking it was
the tag update commit (which we don't want). This patch fixes that by
putting that commit _before_ the tag, which is The Right Way™ anyway, as
it means that the tag will contain the correct version number.
Additionally, I added a way to debug the script a little better with the
`DEBUG=1` environment variable, and quieted the ssh support check.
> chore: fix changelog generation in release script

- src/composition.rs
* **THIS PR**
* https://github.com/influxdata/flux-lsp/pull/555
* https://github.com/influxdata/flux-lsp/pull/556
* https://github.com/influxdata/flux-lsp/pull/557
6. `add_tag()`
* https://github.com/influxdata/flux-lsp/pull/558
* Have composition query be built as a single replacement; and always be built in the same way.
* Note: this also required `bucket` to be collected by the analyzer.
* When any action needs to be taken (e.g. add field, or remove field), we can modify the …
> feat: composition query builder

- src/composition.rs
* https://github.com/influxdata/flux-lsp/pull/554
* https://github.com/influxdata/flux-lsp/pull/555
* https://github.com/influxdata/flux-lsp/pull/556
* **THIS PR**
6. `add_tag()`
* https://github.com/influxdata/flux-lsp/pull/558
Ability to add a tag_value filter to a composition. Also allow adding the next tag_value to the same filter.
DRY with the rest of the infrastructure in the schema composition.
> feat: add_tag_values() for composition.

- src/composition.rs
As a precursor for work on the ResultOptions, we need to have import statements (outside the composition block) be supported. This PR adds tests which demonstrate (and maintains) that the LSP supports this feature.
See current failure (which will be further debugged in the UI) here:
https://github.com/influxdata/ui/issues/6063
> chore(ui-6063): add composition tests which demonstrate support for import statements

- src/composition.rs
This patch enables the user to change the arguments to `range` and have
them be retained by the composition. Prior to this patch, the
composition would just overwrite the `range` arguments to be
`range(start: v.timeRangeStart, stop: v.timeRangeStop)`. Now, if the
user opts to change that range, it is retained over the life of the
composition.
> feat: retain range arguments

- src/composition.rs
This patch guards against a situation where a user might add a new
`filter` call that _looks_ like a schema-oriented filter after any
other flux function call.
Flux sees the datastructures as tables with columns. When those tables
come out of storage, we can be confident that any `filter` is operating
on schema-oriented columns. The moment we see a call not is not one of
`from`|`range`|`filter`, we can no longer be confident that the `filter`
call following it is related to schema.
> feat: escape schema analysis after other calls
